---
- name: "Deploy Portainer to {{ inventory_hostname }}"
  community.docker.docker_container:
    name: portainer
    image: "portainer/portainer:{{ version }}"
    labels: "{{ container_labels | default(omit) }}"
    state: started
    detach: true
    recreate: "{{ container_recreate }}"
    restart_policy: "{{ container_restart_policy }}"
    links: "{{ container_links | default(omit) }}"
    networks: "{{ container_network | default(omit, True) }}"
    networks_cli_compatible: no
    published_ports: "{{ container_ports | default(omit, True) }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ persistent_data_path }}"
  register: portainer_docker

# - name: "Debug return values from container"
#   debug:
#     msg: "{{ portainer_docker.container }}"

- name: Check Protainer container running
  ansible.builtin.set_fact:
    portainer_is_running: "{{ portainer_docker.container.State.Running }}"

- name: Get Protnainer IP address endpoint
  ansible.builtin.set_fact:
    portainer_endpoint: "http://{{ portainer_docker.container.NetworkSettings.IPAddress }}:{{ host_port }}/api"

- name: "Check!!!"
  ansible.builtin.debug:
    msg: "{{ portainer_is_running }} // {{ portainer_endpoint }}"

- name: Check container status
  ansible.builtin.fail:
    msg: "Portainer did not start: {{ portainer_is_running }}"
  when: not portainer_is_running
